Crypto
Liberty-Landing/Liberty-Station-13 pull request #107
Opened 2023-04-23 09:19 UTC by Lamasmaster

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Renames KAZkoin to more generic Koin alongside adding icons to it
	
<hr>
</details>

## Changelog
:cl:
tweak: more generic crypto
imageadd: BonziMoney program icons
/:cl:

2023-04-23 10:47 UTC, ThePainkiller requested changes

2023-04-23 10:47 UTC, ThePainkiller commented on code/modules/modular_computers/file_system/programs/generic/coin_miner.dm
> +	extended_desc = "An endlessly compressed file that when processed turns into valueable credit on the terran market. The bigger the file, the more its worth."
```suggestion
	extended_desc = "An endlessly compressed file that when processed turns into valuable credit on the intergalactic market. The bigger the file, the more its worth."
```

2023-04-23 10:47 UTC, ThePainkiller commented on code/modules/modular_computers/file_system/programs/generic/coin_miner.dm
>  	filedesc = "Key-Authenticated Zipped K-oin"
```suggestion
	filedesc = "Zipped K-oin decoder"
```

2023-04-23 19:22 UTC, Trilbyspaceclone commented
get the sprites approved by Giget

2023-04-24 09:31 UTC, Trilbyspaceclone commented on code/modules/modular_computers/file_system/programs/generic/coin_miner.dm
> +	filedesc = "Zipped K-oin decoder"
two file desc?

2023-04-25 22:51 UTC, AysheDaArtist commented
I'm alright with this for now, but everytime I see it, it's going to be glaring reminder to get it fixed up immediately

I'd prefer some kind of Bonzi Buddy alternative that was more snow themed or lore themed

2023-04-26 06:00 UTC, ThePainkiller commented
> I'd prefer some kind of Bonzi Buddy alternative that was more snow themed or lore themed

A Yeti instead of a monkey, perhaps?

2023-05-01 20:42 UTC, Trilbyspaceclone commented
sorry the sprites are to goofy

2023-05-01 20:42 UTC, closed without merging