Agape_GunCircuits_Logos_HotFixes
Liberty-Landing/Liberty-Station-13 pull request #159
Opened 2023-04-29 20:11 UTC by AysheDaArtist

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Gidgit#0143
-Adds new Render-like enemy: Agape
-Re-Adds in Gun Circuits
-Adds in new logos for Freeport:Liberty
-Hotfixes Engineer clothing pixel shifts

/:cl:

2023-04-29 20:15 UTC, Trilbyspaceclone commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +/mob/living/simple_animal/hostile/render/FindTarget()
is this path correct?

2023-04-29 20:15 UTC, Trilbyspaceclone commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +/mob/living/simple_animal/hostile/render/death(gibbed, deathmessage = "lets out a guttural snarl before it crumbles to the ground dead!")
is this path correct?

2023-04-29 23:48 UTC, ThePainkiller requested changes

2023-04-29 23:48 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +/mob/living/simple_animal/hostile/render/FindTarget()
```suggestion
/mob/living/simple_animal/hostile/agape/FindTarget()
```

2023-04-29 23:48 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +/mob/living/simple_animal/hostile/render/death(gibbed, deathmessage = "lets out a guttural snarl before it crumbles to the ground dead!")
```suggestion
/mob/living/simple_animal/hostile/agape/death(gibbed, deathmessage = "lets out a guttural snarl before it crumbles to the ground dead!")
```

2023-04-29 23:48 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +	special_parts = list(/obj/item/animal_part/render_claw,/obj/item/animal_part/wolf_tooth,/obj/item/animal_part/wolf_tooth)
Might have to rename the "render claw" item as well so that it's in line with the mob

2023-04-29 23:48 UTC, ThePainkiller commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +	meat_type = /obj/item/reagent_containers/food/snacks/meat/primal
Have you checked if the meat is also still listed as "render meat" ?

2023-04-30 03:00 UTC, AysheDaArtist commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +	meat_type = /obj/item/reagent_containers/food/snacks/meat/primal
It is still as render meat, I'll need to get it changed out

2023-04-30 03:01 UTC, AysheDaArtist commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +	special_parts = list(/obj/item/animal_part/render_claw,/obj/item/animal_part/wolf_tooth,/obj/item/animal_part/wolf_tooth)
This is when a Hunter cuts it down with their knife, I can give it it's own parts if we're still using skinning knives

2023-04-30 03:02 UTC, AysheDaArtist commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +/mob/living/simple_animal/hostile/render/FindTarget()
I'll need to add my own path for Agape, but it'll have the same mutations

2023-04-30 03:11 UTC, WatermelonsEverywhere commented on code/modules/mob/living/simple_animal/hostile/big.dm
> +	special_parts = list(/obj/item/animal_part/render_claw,/obj/item/animal_part/wolf_tooth,/obj/item/animal_part/wolf_tooth)
Skinning knives are still at play by Trappers, yes.

2023-04-30 03:29 UTC, AysheDaArtist commented
For now it drops TWO teeth
gives Agape meat that is stat wise the same as Render
All labeled and unique to Agape
Agape for now uses Render sounds

2023-04-30 06:41 UTC, merged