Adds Space Bux
Liberty-Landing/Liberty-Station-13 pull request #175
Opened 2023-04-30 22:03 UTC by Stutternov

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Adds Galactic Credits & renames base credits to Scrip; implying it's Liberty Group company scrip.

Sprites used for Galactic Credits are from Mojave Sun's currency.dmi. I believe made by Inferred Baron. If anyone knows for certain who sprited these besides Inferred, please correct me. Thank you.
	
<hr>
</details>

## Changelog
:cl:
adds: Space bux.......
/:cl:

2023-05-02 02:14 UTC, ThePainkiller requested changes

2023-05-02 02:14 UTC, ThePainkiller commented on code/modules/economy/cash.dm
> +	desc = "It's worth 0 scrip."
```suggestion
	desc = "It's worth 0 scrips."
```

2023-05-03 16:33 UTC, Trilbyspaceclone commented on code/game/machinery/vendor/coalition_vending.dm
> +	icon = 'icons/obj/machines/one_star/vending.dmi'
```suggestion
```

2023-05-03 16:35 UTC, Trilbyspaceclone commented on code/game/machinery/vendor/coalition_vending.dm
> +	icon_vend = "vendor_printing"
their is not carvan_printing

2023-05-03 18:15 UTC, Stutternov commented on code/game/machinery/vendor/coalition_vending.dm
> +	icon_vend = "vendor_printing"
Fixed

2023-05-03 18:36 UTC, merged