Statter
Liberty-Landing/Liberty-Station-13 pull request #261
Opened 2023-05-07 08:42 UTC by Lamasmaster

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Removes anatomy and vivifaction, in place there is now willpower which works as both vivification and serves as something to manage sanity though.
Anatomy has no replacement as it was just used to increase health and nothing else, gamer stat nothing else.
Makes backgrounds bit less punishing.
Buffs negative/positive stat based oddity perks
	
<hr>
</details>

## Changelog
:cl:
add: Willpower
del: Anatomy / Vivification
balance: Backgrounds
balance: Stat based oddity perks
/:cl:

2023-05-07 09:46 UTC, ThePainkiller requested changes

2023-05-07 09:46 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/path/path.dm
> +	stat_modifiers = list(STAT_TGH = 5, STAT_VIG = 10, STAT_MEC = -15)
```suggestion
	stat_modifiers = list(STAT_ROB = 5, STAT_VIG = 10, STAT_BIO = -5, STAT_COG = -10)
```
ROB controls more than TGH ever does, and it's needed for security peeps for shit like aggrograbs and detainment, over just "lose less stamina when holding a shield", VIG and COG sort of balance out each other (not really it's still a loss), gimping MEC this bad is TERRIBLE

2023-05-07 09:46 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/path/path.dm
> +	stat_modifiers = list(STAT_ROB = 10, STAT_COG = 5, STAT_VIG = -10, STAT_WIL = -5)
```suggestion
	stat_modifiers = list(STAT_ROB = -5, STAT_TGH = -5, STAT_COG = 10, STAT_BIO = 3, STAT_MEC = 2, STAT_VIG = -5, STAT_WIL = -5)
```
Free roundstart weapon that can be a good quality katana and shit, same stat gain-lose, extra COG to help with them not being mindbroken at dirty flooring (Willpower being an "extra stat" shouldn't count towards the +/- balance tbh), plus Nobles being usually pushovers that never actually saw combat themselves (education over combat)

2023-05-07 09:46 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/path/path.dm
> +	stat_modifiers = list(STAT_TGH = -5, STAT_MEC = -10, STAT_WIL = 15)
```suggestion
	stat_modifiers = list(STAT_TGH = -10, STAT_COG = -5, STAT_WIL = 15)
```

2023-05-07 09:46 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/path/path.dm
> +	stat_modifiers = list(STAT_ROB = 5, STAT_TGH = 5, STAT_VIG = 5, STAT_MEC = -15)
```suggestion
	stat_modifiers = list(STAT_ROB = 5, STAT_TGH = 5, STAT_VIG = 5, STAT_BIO = -10, STAT_COG = -5)
```
I can't not figure out why would a criminal not learn how to use tools, the thing used the most to commit crime

2023-05-07 09:46 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/path/path.dm
> +	stat_modifiers = list(STAT_ROB = -5, STAT_VIG = -5, STAT_COG = 15, STAT_WIL = -5)
```suggestion
	stat_modifiers = list(STAT_ROB = -5, STAT_TGH = -5, STAT_VIG = -5 STAT_COG = 15)
```

2023-05-07 09:46 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/thoughts/thoughts.dm
> +	stat_modifiers = list(STAT_VIG = 10, STAT_TGH = -10)
```suggestion
	stat_modifiers = list(STAT_VIG = 10, STAT_ROB = -10, STAT_COG = 5, STAT_WIL = -5)
```
Scaredy cat perk with less sanity and noise done, but 50% higher chance to naturally evade traps, basically vigilant and paranoid coward that flees rather than fight

2023-05-07 12:54 UTC, Trilbyspaceclone commented
I dont like ana being removed

2023-05-07 13:03 UTC, Lamasmaster commented
It serves no other purpose than to increase / decrease HP per level it's honestly a dead weight stat in a lot of ways. Considering perks / jobs / races already do that and for the cost it's just not worth it.

2023-05-08 01:44 UTC, Trilbyspaceclone commented
Its intented to be an optional pick for people to play around with and adds.
It has value in that if you have less level up gains though being a race or nanogate picking negitive ana would be better at the start of the shift, as you would scale better at start vs at midpoint/end
If you played a race that leveled up a lot it made you want to invest in it at the start as you would recover the lost points and then some health, making shift join/start slightly weaker but better over the longer round.
If you dont plan on really leveling up then its also a good pick to help round out your character so they are not overly weak all round cuz you didnt want to run around and eat/drink/smoke everything you find

Its completely optional for that reason, it supplements an active choice to do.

2023-05-09 14:06 UTC, merged