help i can hold all these new breakdowns
Liberty-Landing/Liberty-Station-13 pull request #414
Opened 2023-05-29 21:10 UTC by Trilbyspaceclone

Adds in 4 new good breakdowns
Adds in 5 new bad breakdowns

2023-05-29 23:54 UTC, ThePainkiller requested changes
Trilbyfication fixies

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"You sence your hands ready for combat!",
```suggestion
		"You steady your hands for combat!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Weather it's the sight before you, or the acclamations of today you don't feel hungary.",
```suggestion
		"Whether it's your surroundings distracting you, or a matter of focus, hunger is all but gone from you.",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"A knot in your stomach makes you feel not that hungery!",
```suggestion
		"Your stomach no longer growls, your hunger recedes!",
```
Please for the love of god do **NOT** use **that** word here

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Your mind clears letting you think of situations solution!",
```suggestion
		"Your mind clears, letting you think of solutions to your current predicaments!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The mind can slove any problem thrown at it!",
```suggestion
		"The mind can solve any problem thrown at it!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The world floods back losing any brute force thinking.",
```suggestion
		"Your thoughts acclimate, calming down. Your sudden rush of inspiration finally fades.",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Your head fills will rushing throughs, all useless!",
```suggestion
		"Your head fills with rushing throughs, all useless!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"A loud echo fills your head losing any line of thought.",
```suggestion
		"A loud echo fills your head, making you lose any line of thought you had.",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"It's hard to consitrate with all the white noise of the situations around you!",
```suggestion
		"It's hard to focus with all this white noise! I NEED SILENCE!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The calmness comes back to your head.",
```suggestion
		"Your thoughts finally calm down, the noise in your head recedes.",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The worlds heat leaves you!",
```suggestion
		"You suddenly feel heat leave your body, hands freezing, body shivering! It's cold... so cold...",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The chill of the cold reality hits you like a sheet of ice.",
```suggestion
		"You feel a horrible chill down your spine...", // Terraria reference
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Frost comes to the mind, leaving the body shivering!",
```suggestion
		"Your body shivers uncontrollably, has this place always been THIS cold?!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The warm from other sources is required to survive.",
```suggestion
		"Maybe all this cold was just psychosomatic...?",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The reatched sights and smells leave you vomiting outwards.",
```suggestion
		"The wretched sights and smells leave you vomiting outwards.",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The enviroment is to unpleasent for you.",
```suggestion
		"This is too much to handle! I'm feeling sick...!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Your arms feel weak, your legs shakey!",
```suggestion
		"Your arms feel heavy, your knees are weak!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Your body feels like liquid and sways!",
```suggestion
		"You feel like you can barely throw a punch around!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"You feel more soild again and can fight a bit better.",
```suggestion
		"Your fighting instincts are back to you, you feel embarrassed at your lack of control.",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The walls close in your mouth breaths heavily, you must keep your mouth free.",
```suggestion
		"The walls close in, your mouth breaths heavily - everything around you seems bent on not letting you breathe, even what you wear...",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Breathing is so hard, you must keep your mouth free from any objects blocking vital air!",
```suggestion
		"Your throat closes, your words are raspy, this thing in your mouth doesn't let you breathe, take it out!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The thin air makes anything obstructing your mouth feel like you will faint.",
```suggestion
		"This thing in your face is blocking your breathable air! Take it out! TAKE IT OUT! You must breathe!!",
```

2023-05-29 23:54 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The air is thick again and you can give breath with easy."
```suggestion
		"Your hypochondria fades away, your breaths steady themselves as you calm down."
```

2023-05-29 23:55 UTC, ThePainkiller commented
While we're at it, can we please remove the hysteric breakdown that causes you to sob and scream on the floor? It's handled terribly ICly and a bit awkward to properly roleplay that one out or even explain it

2023-05-29 23:57 UTC, Trilbyspaceclone commented on code/modules/sanity/breakdowns.dm
> +		"You feel more soild again and can fight a bit better.",
Emotional feeeeling is trying to be voided atm

2023-05-29 23:57 UTC, Trilbyspaceclone commented on code/modules/sanity/breakdowns.dm
> +		"Breathing is so hard, you must keep your mouth free from any objects blocking vital air!",
These are generlized as they work with or without anything on the mask slot

2023-05-29 23:59 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"You feel more soild again and can fight a bit better.",
Oke, editing so that it's out

2023-05-31 03:54 UTC, Trilbyspaceclone commented on code/modules/sanity/breakdowns.dm
> +		"The thin air makes anything obstructing your mouth feel like you will faint.",
What if theirs nothing on your face?

2023-05-31 03:55 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"Breathing is so hard, you must keep your mouth free from any objects blocking vital air!",
Alright, fair!

2023-05-31 03:56 UTC, ThePainkiller commented on code/modules/sanity/breakdowns.dm
> +		"The thin air makes anything obstructing your mouth feel like you will faint.",
Good point, nevermind this one

2023-06-01 03:46 UTC, merged