fixes some nulling
Liberty-Landing/Liberty-Station-13 pull request #475
Opened 2023-07-30 04:01 UTC by Trilbyspaceclone

Fixes an error with gereration with card carp cards
Fixes an error with allowing you to null cells/items when crafting items using storage items or other tools/devices

2023-07-30 04:05 UTC, ThePainkiller requested changes

2023-07-30 04:05 UTC, ThePainkiller commented on code/datums/craft/step.dm
> +			to_chat(user, SPAN_WARNING("Their is something inside [I] that must be removed before crafting this!"))
```suggestion
			to_chat(user, SPAN_WARNING("There is something inside \the [I] that must be removed before using it to craft!"))
```

2023-07-30 04:05 UTC, ThePainkiller commented on modular_liberty/cardgame_2/cardgame_2.dm
> +		name = "Redink [new_name]"
What's "Redink"...?

2023-07-31 12:32 UTC, Trilbyspaceclone commented on modular_liberty/cardgame_2/cardgame_2.dm
> +		name = "Redink [new_name]"
Its the opposed to blackink and blueink is used already

2023-07-31 12:32 UTC, Trilbyspaceclone commented on code/datums/craft/step.dm
> +			to_chat(user, SPAN_WARNING("Their is something inside [I] that must be removed before crafting this!"))
Their not there

2023-07-31 15:58 UTC, merged

2023-08-01 22:46 UTC, ThePainkiller commented on code/datums/craft/step.dm
> +			to_chat(user, SPAN_WARNING("Their is something inside [I] that must be removed before crafting this!"))
This is...not gramatically correct Trilby...
"there is" = indicates something exists in that location
"their" = indicates that the object in question is possessed by someone you are referring to