balances in character creation
Liberty-Landing/Liberty-Station-13 pull request #495
Opened 2023-09-06 19:38 UTC by Dorodomki

## About The Pull Request

for some reason someone buffed the early start of the characters going with +5 and +10 stat points in some areas, this reverts the clearly convenient start for some characters since is not fair.

## Changelog
:cl:
balance: nerfs some stat points in character creation for humans
/:cl:
¡

2023-09-09 03:26 UTC, ThePainkiller requested changes

2023-09-09 03:26 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm
> +	stat_modifiers = list(STAT_COG = 5, STAT_BIO = 5, STAT_VIG = 5) //Pretty bad perk baked into this so//pretty unbalanced start for a character so is going with 5 as every other ancestry.
```suggestion
	stat_modifiers = list(STAT_COG = 5, STAT_BIO = 5, STAT_MEC = 5) //Pretty bad perk baked into this so
```
No combat stats on Sol Born.

2023-09-09 03:26 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/thoughts/thoughts.dm
> +	stat_modifiers = list(STAT_WIL = 5, STAT_ROB = 5, STAT_TGH = 5, STAT_VIG = 5, STAT_COG = -10)//the willpower is a strong stat and shouldn't be that high on the start of shift
Where did you get the idea that Willpower is a strong stat? Do you have any idea what it controls? More than half of what it does is gated behind psionics, which are currently completely disabled, and we don't have bears on the map for the growl check either, the ONLY thing they affect are two things: Sanity damage when witnessing deaths and NSA, and the later is literally a lazy thing that was done when Vivification and Anatomy were removed in lieu for this, and it still isn't as busted as you think it is.
Willpower being strong on a literal background that is **designed** to freak out less in tunnels is literally a design choice, it's not like max HP.

2023-09-09 03:26 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/thoughts/thoughts.dm
> +	stat_modifiers = list(STAT_WIL = 5, STAT_ROB = 5, STAT_TGH = 5, STAT_VIG = 5, STAT_COG = -10)//the willpower is a strong stat and shouldn't be that high on the start of shift
```suggestion
	stat_modifiers = list(STAT_WIL = 10, STAT_ROB = 5, STAT_TGH = 5, STAT_VIG = 5, STAT_COG = -10) // High willpower on a perk designed to freak out less at death
```

2023-09-09 03:26 UTC, ThePainkiller commented on code/datums/setup_option/backgrounds/thoughts/thoughts.dm
> +	stat_modifiers = list(STAT_WIL = 5, STAT_COG = -5, STAT_BIO = -5)
```suggestion
	stat_modifiers = list(STAT_WIL = 10, STAT_COG = -5, STAT_BIO = -5)
```
Stats are balanced on the same -10 / +10 mentality unless perks with negative drawbacks are taken into account
Nerfing this unnecessarily makes the perk literally undesireable to even take. At least split it on another positive if you want to nerf its WIL.

2023-09-15 17:14 UTC, Trilbyspaceclone commented on code/datums/setup_option/backgrounds/path/path.dm
> +	stat_modifiers = list(STAT_BIO = 15, STAT_TGH = 5, STAT_MEC = -10)//the medic path was too unbalanced with the previous stats so is going down, the "combat medic" can be part of the character backgr
```suggestion
	stat_modifiers = list(STAT_BIO = 15, STAT_TGH = 5, STAT_MEC = -10) 
```

2023-09-16 00:47 UTC, merged