NEV Port - Consciousness Backup Implant
Liberty-Landing/Liberty-Station-13 pull request #95
Opened 2023-04-19 15:11 UTC by Stutternov

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Tl;dr - attempts to add a core implant for cloning purposes. Why? You'll see.
	
<hr>
</details>

## Changelog
:cl:
adds: Consciousness backup implant
/:cl:

2023-04-20 23:23 UTC, ThePainkiller commented
I believe in Hestia/Vesta/Whatever this was called a...Neural Lace, I believe? The implant that you could opt on character setup that allowed your body to be cloned since it "stored all the information about yourself", the process was to take that off the dead body, slap the corpse on the scanner, clone a new body, insert the Neural Lace on the new clone's head, then defib back to life. Will this be the same process? I need to know to start writing lore behind this.

2023-04-21 00:31 UTC, ThePainkiller requested changes

2023-04-21 00:31 UTC, ThePainkiller commented on code/modules/core_implant/cruciform/machinery/cloning.dm
> +	desc = "A strangely advanced machine that scans the user for any signs existing conciousness through brainwaves. \
```suggestion
	desc = "A strangely advanced machine that scans the user for any signs of existing conciousness through magnetic resonance imaging. \
```

2023-04-21 00:31 UTC, ThePainkiller commented on code/modules/core_implant/cruciform/machinery/cloning.dm
> +			Used to check if a user's conciousness backup implant has remained intact; allowing the transfer of conciousness to a new body."
```suggestion
			Used to check if a user's conciousness backup implant has remained intact, allowing the transfer of conciousness to a new body."
```

2023-04-22 00:20 UTC, Stutternov commented
> I believe in Hestia/Vesta/Whatever this was called a...Neural Lace, I believe? The implant that you could opt on character setup that allowed your body to be cloned since it "stored all the information about yourself", the process was to take that off the dead body, slap the corpse on the scanner, clone a new body, insert the Neural Lace on the new clone's head, then defib back to life. Will this be the same process? I need to know to start writing lore behind this.

Right, so - overall this device is designed to do something semi-similar lore wise.

The general idea is that it holds an engram of your consciousness and DNA; so even after you die your consciousness will be backed up onto the device. Effectively leaving your body 'dead' but saving what would be determined as your consciousness into the device; allowing a 'life-after-death' effectively.

This will **NOT** be for setup upon decision; this will instead be an implant type CAPSA can make with a new implant fabricator they'll be getting (allows construction of psionic implants, death alarms, and Con-Backs for now). This will effectively be a 'trade-off' implant, disallowing the usage of psionics and death alarms but allowing you, if you have enough energy loaded in the thing, to be revived post-death.

The reason these will not be in setup lore wise is a 'low shelf life' or something to that effect. The backup only realistically lasting for so long.

2023-04-22 16:50 UTC, merged